// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zbyjrchtprxjpagprvfl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpieWpyY2h0cHJ4anBhZ3BydmZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk5MTg1NzcsImV4cCI6MjA3NTQ5NDU3N30.QUAvFF7c0w2Oi2raXmmWd_wtnOxP2vKbLvpsICkA65A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});